apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: geolocationmock-go
build:
  local:
    push: false
  artifacts:
  - image: geolocationmock-go
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
deploy:
  kubectl:
    manifests:
    - deploy/k8s/deployment.yaml
    - deploy/k8s/service.yaml
    - deploy/k8s/serviceaccount.yaml
